combine cetaceans :whale2: and fish and invertebrates :fish: sections…
dfo-mar-odis/shinySpatialApp pull request #71
Opened 2022-04-28 18:55 UTC by stoyelq

Combines these two sections into a single large section.   #68

@gomezcatalina does the text at the start of the cetaceans section need to modified / where should this go?  

@stfinnis: does any of the OBIS section need to be updated because it's now just one section?  I did update the table and figure captions, but I may have missed things.

2022-04-28 18:56 UTC, stoyelq commented on app/templates/EN/species/species.Rmd
>  This module summarizes cetacean (whale and dolphins) information available from various DFO and non-DFO sources, including visual sightings, and modeled predictions. Outputs from each data source are
Does this block of text need to be updated? @gomezcatalina

2022-04-29 14:16 UTC, stfinnis requested changes
From what I can tell, you haven't missed anything from merging the OBIS/GBIF fish & inverts/cetacean sections. Thank you for doing this! I'll let Catalina comment about the overall Cetaceans text.
I just provided to comments about updating the OBIS/GBIF information in the obisCommon_en.Rmd so it has current (April 2022) information.
Probably the OBIS/GBIF references in the bib file and in-text citations should also be changed from 2021 --> 2022. I'm still not totally sure how pull requests work. Do I just identify the problem here, or should I actually make these changes (here? or in a separate pull request?) so you don't have to?

2022-04-29 16:19 UTC, stfinnis approved these changes

2022-04-29 19:27 UTC, gomezcatalina requested changes
Proposing the creation of a slightly different Table of Contents to accommodate our brand new amalgamated "Species" tab. We may need @stfinnis :mage: magic powers to advice and word smith. I'll create a meeting to explore options.

2022-04-29 19:27 UTC, gomezcatalina commented on app/templates/EN/species/species.Rmd
>  This module summarizes cetacean (whale and dolphins) information available from various DFO and non-DFO sources, including visual sightings, and modeled predictions. Outputs from each data source are
mmm... maybe a bit... particularly where to place that text exactly. We may need to arrange things (ToC) a bit and update headers? And the wording between modules and sections? :confused: At the moment, we have main headers for modules, which are the items that can be selected via the Shinny App e.g. "Species", "Aquatic Invasive Species", "Habitat"... We have secondary headers for sections, which correspond to information summarized in the modules. By merging cetaceans and fish/inverts, we have a whole section specifically for cetaceans... but we do not have something like this for fish/invertebrates. What if we create a section, within the new Species module, so the table of contents will look like:

**SPECIES MODULE**

_INFORMATION FROM THE NATIONAL AQUATIC SPECIES AT RISK GEODATABASE_

_DATASETS FOR MULTIPLE SPECIES_

- obis
- ...

_FISH AND INVERTEBRATES DATASETS_

- RV Survey...

_CETACEAN DATASETS_

- wsdb...

2022-05-04 14:50 UTC, gomezcatalina approved these changes
Merge of section with new updates ToC looks great :star2:

2022-05-04 14:52 UTC, merged